### ISSUE TITLE
cf install-plugin command fails on 

### ISSUE THREAD

**Issue by fabianleh** [cloudfoundry/multiapps-cli-plugin#150]
Dear all,

I try to execute the following command on my Apple M1 Max MBP to install the multiapps-cli-plugin:

`cf install-plugin -f https://github.com/cloudfoundry-incubator/multiapps-cli-plugin/releases/latest/`

I get the following error as response, any idea how to resolve the problem?:

```
download/multiapps-plugin.linux32 
Attention: Plugins are binaries written by potentially untrusted authors.
Install and use plugins at your own risk.
Starting download of plugin binary from URL...
 13.16 MiB / 13.16 MiB [================================================================================] 100.00% 0s
fatal: morestack on g0
SIGTRAP: trace trap
PC=0x80a8712 m=1 sigcode=128

goroutine 0 [idle]:
runtime.abort()
        /usr/local/go/src/runtime/asm_386.s:843 +0x2
runtime.morestack()
        /usr/local/go/src/runtime/asm_386.s:437 +0x24

goroutine 1 [running, locked to thread]:
        goroutine running on other thread; stack unavailable

eax    0x17
ebx    0x2
ecx    0x857b2a1
edx    0x17
edi    0x86f71b9
esi    0x8c002a0
ebp    0x0
esp    0x8c3c668
eip    0x80a8712
eflags 0x202
cs     0x23
fs     0x0
gs     0x33
exit status 2
File is not a valid cf CLI plugin binary.
FAILED
```

cf version:
cf version 6.53.0+8e2b70a4a.2020-10-01

cf is running inside a docker (alpine linux v3.15) container

thx

**Comment by radito3** [comment]
Hello,
It seems like you are trying to install a linux 32-bit binary on an Apple product, which run OS X.
My recommendation is to manually download the binary first https://github.com/cloudfoundry-incubator/multiapps-cli-plugin/releases/latest/download/multiapps-plugin.osx and then use _cf install-plugin multiapps-plugin.osx -f_.

Also, version 6 of the CF CLI is deprecated. v7 is recommended.

**Comment by fabianleh** [comment]
Hi @radito3,

thx for the hint with the version, we switched to v7. 
We are running [Alpine](https://hub.docker.com/_/alpine) inside a Docker container where we want to install the plugin.
Therefore this should work, isn't it (works before I switched to a M1 MBP)?

thx

**Comment by radito3** [comment]
Hello @fabianleh ,

I am confused.
Are you trying to deploy _inside_ a container or on your Apple device?
Either way, a 64-bit executable is recommended.
If it's a containerized deployment, please try the _.linux64_ binary (with v7 cli).
If it's on the new M1 Mac, there is an issue with the CF CLI on the new Apple chipset https://github.com/cloudfoundry/cli/issues/2131 .
To deploy on your laptop, please take a look at this article https://indiespark.top/software/run-command-line-apple-silicon/

Best regards,
Rangel

**Comment by JuBerndt** [comment]
Hello,
i have another installation problem using the windows 64Bit file.
I tried several steps, versions and environments for installation of the plugin.
Stop, change Firewall settings etc.
The error i always got is:

`C:\>cf install-plugin -f https://github.com/cloudfoundry-incubator/multiapps-cli-plugin/releases/latest/download/multiapps-plugin.win64.exe
Attention: Plugins are binaries written by potentially untrusted authors.
Install and use plugins at your own risk.
Starting download of plugin binary from URL...
 15.30 MiB / 15.30 MiB [===========================================================================================================================================================================] 100.00% 2s
dial tcp 127.0.0.1:57368: connectex: Access to a socket was not allowed due to the socket's permissions.
exit status 1
File is not a valid cf CLI plugin binary.
FAILED`

I looking on the internet for a solution, but all the hint's did not help.
Which specific setting i have to change, to install the plugin on my Windows 10 machine ?

Kind Regards
Jürgen

**Comment by theghost5800** [comment]
Hi @JuBerndt , you can either use CF-Community repo to download automatically the plugin - https://github.com/cloudfoundry/multiapps-cli-plugin#cf-community-plugin-repository or download manually the binary on your machine with the browser and execute this command `cf install-plugin <path-to-the-plugin-on-filesystem> -f`

**Comment by JuBerndt** [comment]
> Hi @JuBerndt , you can either use CF-Community repo to download automatically the plugin - https://github.com/cloudfoundry/multiapps-cli-plugin#cf-community-plugin-repository or download manually the binary on your machine with the browser and execute this command `cf install-plugin <path-to-the-plugin-on-filesystem> -f`

I have done it before, downloaded to the pc, tried to install etc.
Always the same error.
I'm playing arround with the Windows Firewall, Defender etc. to shut down all of them and trying again.
Actually the same error.

Regards
Jürgen

**Comment by ThePlenkov** [comment]
Hi! I'm facing same issue. Here is my dockerfile
```
FROM mcr.microsoft.com/devcontainers/typescript-node:1-20-bullseye

RUN wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
RUN echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list

# install Linux packages
RUN sudo apt-get update 
RUN sudo apt-get install cf8-cli

# install npm packages
RUN npm install -g mbt @sap/cds-dk

# addtional plugins to Cloud Foundry
RUN cf install-plugin -r CF-Community "multiapps"
RUN cf install-plugin -f multiapps
```

somehow the last command fails
```
f install-plugin -f multiapps
Searching CF-Community for plugin multiapps...
Plugin multiapps 3.2.1 found in: CF-Community
Attention: Plugins are binaries written by potentially untrusted authors.
Install and use plugins at your own risk.
Starting download of plugin binary from repository CF-Community...
 15.91 MiB / 15.91 MiB [================================================================================================================================================================] 100.00% 2s
/home/node/.cf/plugins/temp1591990395/3838909457: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/node/.cf/plugins/temp1591990395/3838909457)
/home/node/.cf/plugins/temp1591990395/3838909457: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /home/node/.cf/plugins/temp1591990395/3838909457)
exit status 1
File is not a valid cf CLI plugin binary.
FAILED
```

Do you have any workaround for this solution?

It seems like the problem is caused by the arcitecture indeed, but i'm running

**Comment by ThePlenkov** [comment]
Actually checking the version using `ldd --version` i found that I had libc6 2.31 which is indeed not what the app expected. I decided to increase the OS level to bookworm instead of bullseye and it worked because it has libc6 2.36.

**Comment by theghost5800** [comment]
Hi @ThePlenkov , described issue from your side is more relevant to this one https://github.com/cloudfoundry/multiapps-cli-plugin/issues/186 . With release of plugin version 3.1.0 and newer versions, we switched to Go 1.20 and glibc required version was also increased. So in order to use latest version, you need to use newer OS version/docker base image.

I will resolve this issue due to inactivity, if the original issue it's still relevant, please reopen it.
