### ISSUE TITLE
File is not a valid cf CLI plugin binary (CF-CLI v8.6.1 / Docker)

### ISSUE THREAD

**Issue by xLexip** [cloudfoundry/multiapps-cli-plugin#163]
Hey there, 

I got the following issue with the docker image [cloudfoundry/cli:8](https://hub.docker.com/layers/cloudfoundry/cli/8/images/sha256-571eee4e60f83cad6467011eaddf8588111208dec14461c9ccd1d73b12f7e9e6?context=explore) (v8.6.1+b5a352a.2023-02-27). Am I missing something or isn't this supposed to run with this version?

```
Using Kubernetes executor with image cloudfoundry/cli:8 ...

$ cf --version
cf version 8.6.1+b5a352a.2023-02-27

$ cf install-plugin -r CF-Community "multiapps" -f
Searching CF-Community for plugin multiapps...
Plugin multiapps 3.0.2 found in: CF-Community
Attention: Plugins are binaries written by potentially untrusted authors.
Install and use plugins at your own risk.
Starting download of plugin binary from repository CF-Community...
 0 B / 15.44 MiB    0.00%
 15.44 MiB / 15.44 MiB  100.00% 0s
fork/exec /root/.cf/plugins/temp1[31] 5574591/1195806702: no such file or directory
File is not a valid cf CLI plugin binary.
FAILED
```

BR
Lexip

**Comment by IvanBorislavovDimitrov** [comment]
Hello Lexip,

You see this issue because the artifacts uploaded in GitHub and in the CF-Comunity repo are not statically built and the image that cloudfoundry/cli:8 is based on is alpine which does not have the required C libraries.
We are considering to upload statically built artifacts in GitHub.
As of now I can suggest to clone the project, and run the "build.sh" script. This will generate the statically built artifacts in the newly created "build" directory. Then you can copy and install it during the Dockerfile build:

COPY ./multiapps-plugin-static.linux64 ./
RUN cf install-plugin "multiapps-plugin-static.linux64" -f

Best regards,
Ivan

**Comment by xLexip** [comment]
Good morning @IvanBorislavovDimitrov,

thanks for your reply and the suggested solution. Nevertheless, I would appreciate a working and up-to-date Docker image in general, as it currently uses v8.6.1.

BR
Lexip
